name: Trigger repository dispatch event
on:
  push:
    branches:
      - main
      - dev
jobs:
  dispatch:
    name: Repository Dispatch
    runs-on: ubuntu-latest
    if: github.repository_owner == 'WEC-Sim'
    steps:
    - uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: WEC-Sim/WEC-Sim_Applications
        event-type: wecsim-${{ github.ref_name }}
        client-payload: '{"sha": "${{ github.sha }}", "branch": "${{ github.ref_name }}"}'
